travis:
  secure:
    BINSTAR_TOKEN: V92Ue4eXwdN6PH/UupL8hIT25zZFqSUOz5HUmFuJEQkNSxZHKCLwMAjxXJsJJe70h5gKvKKeqRhTV9GWLD9VAl5pH5NmjlrLkpKH0eJWjXv8LKA6lbgdgO+Cb2dUqNnzKSudlQC+dgGv+ZSfzXDzJYjau57aGdJQHI0Iz/cutn+5Wd5eJOEuHRnPsrUw78CypbaZ+jw7UxoYYY6NL3POXBC+xdUJlIed00V0b+zKTav+7XZKTqFR3ai871R28Q2sNm8Z2/tspEwp03vB3tssc80ZFZkhK8ruX2/J+DUgqtniHUJ72GjIEGlUdx+AvVb23HlZfPqmR2IPfB62rv8TSGFDGR5hoTOVsDtZi7nmUk1ywklvR0hv3dCv7piau4j9MW3T8s/Wu1oRoeWpDOFBDtG2AflC+IhJKUYCTTwG21gMTPwDGnVN2c4jUo3WnFPtL3sWH3bqGWJK+v7kNHsTrKnYg7uRE/9PWsIlVFfxXEu3P0KcFvQTvsJs7su9f0lIrlQ1C81toWgZYxAJQUXVwi16jSpiGyqSbC4enPWsEOrpd2zb0Yk/wHCenPb7SsYqNgzMf77j1u9h/0+zIzYT08fgH7vX22xN82vNlY1SV6QVCGA8Y7VxefYOZdlfGwpMFQ1YK7tfy8AAmfGXdpfBW5+tkyXTE77Ac8xt8QkjuoU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
